---
# ansible -m copy -a "src=../adhoc/master.gitconfig dest=~/.gitconfig" localhost

# This is a play
- name: run copy task on localhost
  hosts: localhost
  tasks:
  - copy:
      src: "master.gitconfig"
      dest: "~/.gitconfig"

# This is another play
- name: install cheat on localhost
  hosts: localhost
  tasks:
  - pip:
      name: cheat
  #- pip: name=cheat   
 